#!/usr/bin/env node
/**
 * Ouracle Service Worker
 * Cache-busting strategy: versioned cache names with hash-based content addressing
 * Dev mode: Cache-Control: no-cache, aggressive busting
 * Prod mode: Versioned static assets, runtime API calls bypass cache
 */

const CACHE_VERSION = 'v2.0.0'; // Increment on every deploy
const STATIC_CACHE = `ouracle-static-${CACHE_VERSION}`;
const RUNTIME_CACHE = `ouracle-runtime-${CACHE_VERSION}`;

// Files to precache (generated by Vite build, matched by glob)
const STATIC_ASSETS = [
  '/',
  '/index.html',
  '/manifest.json',
  '/favicon.ico',
  '/apple-touch-icon.png',
  '/android-chrome-192x192.png',
  '/android-chrome-512x512.png',
  // SvelteKit assets will be injected by Vite plugin
];

// Dev mode detection: check for ?_nocache or unversioned build
const isDev = typeof self.registration !== 'undefined' &&
  self.registration.scope.includes('_nocache') ||
  !CACHE_VERSION.match(/^v\d+\.\d+\.\d+$/);

self.addEventListener('install', (event) => {
  console.log('[SW] Installing...');
  event.waitUntil(
    caches.open(STATIC_CACHE)
      .then((cache) => {
        console.log('[SW] Pre-caching static assets');
        return cache.addAll(STATIC_ASSETS);
      })
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  console.log('[SW] Activating...');
  event.waitUntil(
    // Clean old caches
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames
          .filter((name) => name.startsWith('ouracle-'))
          .filter((name) => name !== STATIC_CACHE && name !== RUNTIME_CACHE)
          .map((name) => caches.delete(name))
      );
    }).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // Skip non-GET requests
  if (request.method !== 'GET') return;

  // Bypass cache for API calls (MEATAPI)
  if (url.pathname.startsWith('/api/') || url.hostname !== location.hostname) {
    event.respondWith(
      fetch(request).catch(() => {
        // Offline fallback for API: show friendly message
        return new Response(JSON.stringify({
          error: 'Network unavailable — Ouracle requires connection to MEATAPI',
          offline: true
        }), {
          headers: { 'Content-Type': 'application/json' }
        });
      })
    );
    return;
  }

  // Handle static assets: cache-first with network fallback
  if (isStaticAsset(url) || url.pathname.endsWith('.svelte') || url.pathname.match(/\.(js|css|png|jpg|jpeg|gif|svg|webp|ico|woff2?)$/i)) {
    event.respondWith(
      caches.match(request)
        .then((cached) => {
          if (cached) {
            // Dev mode: always revalidate
            if (isDev) {
              return fetch(request).then((networkResponse) => {
                caches.open(STATIC_CACHE).then((cache) => cache.put(request, networkResponse.clone()));
                return networkResponse;
              });
            }
            return cached;
          }
          return fetch(request)
            .then((response) => {
              return caches.open(STATIC_CACHE).then((cache) => {
                cache.put(request, response.clone());
                return response;
              });
            });
        })
    );
    return;
  }

  // HTML navigation requests: network-first with cache fallback for SPA
  if (request.headers.get('accept', '').includes('text/html')) {
    event.respondWith(
      fetch(request)
        .then((response) => {
          // Update cache with fresh HTML
          return caches.open(STATIC_CACHE).then((cache) => {
            cache.put(request, response.clone());
            return response;
          });
        })
        .catch(() => {
          return caches.match(request).then((cached) => {
            if (cached) return cached;
            // Offline fallback page
            return caches.match('/offline.html');
          });
        })
    );
    return;
  }

  // Runtime cache for other assets (images, fonts from CDN): stale-while-revalidate
  event.respondWith(
    caches.match(request)
      .then((cached) => {
        const fetchPromise = fetch(request)
          .then((response) => {
            if (response.ok) {
              caches.open(RUNTIME_CACHE).then((cache) => cache.put(request, response.clone()));
            }
            return response;
          });
        return cached || fetchPromise;
      })
  );
});

function isStaticAsset(url) {
  return url.pathname.startsWith('/_app/') ||
         url.pathname.startsWith('/assets/') ||
         url.pathname === '/';
}